- name: Download activator
  shell: |
    cd /usr/local/src &&
    wget http://downloads.typesafe.com/typesafe-activator/1.2.10/typesafe-activator-1.2.10-minimal.zip
    unzip typesafe-activator-1.2.10-minimal.zip

- name: Setup activator
  shell: |
    sudo mv /usr/local/src/activator-1.2.10-minimal/ /usr/local &&
    cd /usr/bin &&
    sudo ln -s /usr/local/activator-1.2.10-minimal/activator activator

#- name: Download play framework
#  shell: |
#    cd ~ &&
#    wget http://downloads.typesafe.com/play/2.2.3/play-2.2.3.zip &&
#    unzip play-2.2.3.zip

#- name: Setup play framework
#  shell: |
#    sudo mv ~/play-2.2.3/ /usr/local &&
#    cd /usr/bin &&
#    sudo ln -s /usr/local/play-2.2.3/play play

